version: '3'
services:
    agent-1:
        container_name: inmanta_agent_1
        image: inmanta-agent
        build:
            context: "./agent"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
        networks:
            testing_net:
                ipv4_address: 172.28.0.4
        ports:
            - "8080:80"

    agent-2:
        container_name: inmanta_agent_2
        image: inmanta-agent
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
        networks:
            testing_net:
                ipv4_address: 172.28.0.5



networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
